import Foundation
import SwiftData
import XCTest
@testable import Documents

/// A failed record save must roll back the pending model and clean up only
/// files created by the operation. Adopted files already existed and must be
/// preserved when their record cannot be persisted.
@MainActor
final class DocumentStoreCreationFailureTests: XCTestCase {
    private var tempRoot: URL!
    private var documentsDir: URL!
    private var sourcesDir: URL!
    private var container: ModelContainer!
    private var store: DocumentStore!

    override func setUp() async throws {
        try await super.setUp()
        tempRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("DocumentStoreCreationFailureTests-" + UUID().uuidString, isDirectory: true)
        documentsDir = tempRoot.appendingPathComponent("Documents", isDirectory: true)
        sourcesDir = tempRoot.appendingPathComponent("Sources", isDirectory: true)
        try? FileManager.default.createDirectory(at: sourcesDir, withIntermediateDirectories: true)

        let configuration = ModelConfiguration(isStoredInMemoryOnly: true)
        container = try! ModelContainer(for: DocumentRecord.self, configurations: configuration)
        store = DocumentStore(
            context: container.mainContext,
            fileBridge: FileBridge(documentsDirectory: documentsDir)
        )
    }

    override func tearDown() async throws {
        try? FileManager.default.removeItem(at: tempRoot)
        tempRoot = nil
        documentsDir = nil
        sourcesDir = nil
        container = nil
        store = nil
        try await super.tearDown()
    }

    private struct InjectedSaveFailure: Error {}

    private func makeSourceFile(named name: String, contents: String = "source bytes") throws -> URL {
        let url = sourcesDir.appendingPathComponent(name)
        try contents.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func allRecords() throws -> [DocumentRecord] {
        try store.context.fetch(FetchDescriptor<DocumentRecord>())
    }

    private func fileExists(_ relativePath: String) -> Bool {
        FileManager.default.fileExists(atPath: documentsDir.appendingPathComponent(relativePath).path)
    }

    private func failNextSave() {
        store.saveFailureForTesting = InjectedSaveFailure()
    }

    func testImportSaveFailureRollsBackRecordAndCopiedFile() throws {
        let source = try makeSourceFile(named: "Report.pdf")
        failNextSave()

        XCTAssertThrowsError(try store.importFile(from: source))
        XCTAssertTrue(try allRecords().isEmpty)
        XCTAssertTrue(try store.fetchRecent().isEmpty)
        XCTAssertFalse(fileExists("Report.pdf"))
        XCTAssertTrue(FileManager.default.fileExists(atPath: source.path))

        store.saveFailureForTesting = nil
        let retry = try store.importFile(from: source)
        XCTAssertEqual(retry.relativePath, "Report.pdf")
        XCTAssertFalse(fileExists("Report (1).pdf"))
        XCTAssertEqual(try allRecords().map(\.id), [retry.id])
    }

    func testGeneratedFileSaveFailureRollsBackRecordAndGeneratedFile() throws {
        let payload = Data("generated bytes".utf8)
        failNextSave()

        XCTAssertThrowsError(
            try store.saveGeneratedFile(name: "Generated/Result.pdf", data: payload)
        )
        XCTAssertTrue(try allRecords().isEmpty)
        XCTAssertTrue(try store.fetchRecent().isEmpty)
        XCTAssertFalse(fileExists("Generated/Result.pdf"))

        store.saveFailureForTesting = nil
        let retry = try store.saveGeneratedFile(name: "Generated/Result.pdf", data: payload)
        XCTAssertEqual(retry.relativePath, "Generated/Result.pdf")
        XCTAssertFalse(fileExists("Generated/Result (1).pdf"))
        XCTAssertEqual(try Data(contentsOf: documentsDir.appendingPathComponent(retry.relativePath)), payload)
        XCTAssertEqual(try allRecords().map(\.id), [retry.id])
    }

    func testCreateDocumentSaveFailureRollsBackRecordAndCreatedFile() throws {
        failNextSave()

        XCTAssertThrowsError(
            try store.createDocument(named: "Ideas", fileExtension: "md", contents: "# Ideas\n")
        )
        XCTAssertTrue(try allRecords().isEmpty)
        XCTAssertTrue(try store.fetchRecent().isEmpty)
        XCTAssertFalse(fileExists("Ideas.md"))

        store.saveFailureForTesting = nil
        let retry = try store.createDocument(named: "Ideas", fileExtension: "md", contents: "# Ideas\n")
        XCTAssertEqual(retry.relativePath, "Ideas.md")
        XCTAssertFalse(fileExists("Ideas (1).md"))
        XCTAssertEqual(
            try String(contentsOf: documentsDir.appendingPathComponent(retry.relativePath), encoding: .utf8),
            "# Ideas\n"
        )
        XCTAssertEqual(try allRecords().map(\.id), [retry.id])
    }

    func testAdoptSaveFailureRollsBackRecordAndPreservesExistingFile() throws {
        let source = try makeSourceFile(named: "Granted.pdf", contents: "external bytes")
        failNextSave()

        XCTAssertThrowsError(
            try store.adoptFile(at: source, provenance: .device, absolutePath: source.path)
        )
        XCTAssertTrue(try allRecords().isEmpty)
        XCTAssertTrue(try store.fetchRecent().isEmpty)
        XCTAssertTrue(FileManager.default.fileExists(atPath: source.path))
        XCTAssertEqual(try Data(contentsOf: source), Data("external bytes".utf8))

        store.saveFailureForTesting = nil
        let retry = try store.adoptFile(at: source, provenance: .device, absolutePath: source.path)
        XCTAssertEqual(retry.absolutePath, source.path)
        XCTAssertEqual(try allRecords().map(\.id), [retry.id])
        XCTAssertEqual(try Data(contentsOf: source), Data("external bytes".utf8))
    }
}
