import Foundation

/// Errors surfaced by filesystem bridge operations.
enum FileBridgeError: LocalizedError {
    case deletionFailed(relativePath: String, underlying: any Error)

    var errorDescription: String? {
        switch self {
        case .deletionFailed:
            "The file could not be deleted."
        }
    }
}

/// Filesystem bridge between the document store and the app container.
///
/// All imported documents live inside the app container's Documents directory.
/// The store only persists container-relative paths; this type resolves them,
/// performs copy-into-container imports, dedupes colliding names with a
/// " (n)" suffix, and handles physical deletion.
struct FileBridge: Sendable {
    let documentsDirectory: URL

    init(documentsDirectory: URL = FileBridge.defaultDocumentsDirectory) {
        self.documentsDirectory = documentsDirectory
    }

    /// The app container's Documents directory.
    static var defaultDocumentsDirectory: URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
    }

    struct ImportedFile: Sendable {
        let url: URL
        let sizeBytes: Int64
    }

    @discardableResult
    func ensureDocumentsDirectory() throws -> URL {
        try FileManager.default.createDirectory(
            at: documentsDirectory,
            withIntermediateDirectories: true
        )
        return documentsDirectory
    }

    /// Copies `sourceURL` into the container Documents directory (copy, never
    /// move) and returns the destination plus its size. Handles
    /// security-scoped URLs handed over by the document picker.
    func importFile(from sourceURL: URL) throws -> ImportedFile {
        let scoped = sourceURL.startAccessingSecurityScopedResource()
        defer {
            if scoped { sourceURL.stopAccessingSecurityScopedResource() }
        }
        try ensureDocumentsDirectory()
        let destination = uniqueDestinationURL(for: sourceURL.lastPathComponent, in: documentsDirectory)
        try FileManager.default.copyItem(at: sourceURL, to: destination)
        return ImportedFile(url: destination, sizeBytes: Self.fileSize(at: destination))
    }

    /// Creates a new text file in the container with the given contents.
    @discardableResult
    func createFile(named filename: String, contents: String) throws -> URL {
        try ensureDocumentsDirectory()
        let destination = uniqueDestinationURL(for: filename, in: documentsDirectory)
        try contents.write(to: destination, atomically: true, encoding: .utf8)
        return destination
    }

    /// Writes generated bytes (toolbox/scanner/converter output) into the
    /// container. The name may contain subfolders ("Images_Report/1.jpg");
    /// intermediate directories are created as needed.
    @discardableResult
    func writeGeneratedFile(named filename: String, data: Data) throws -> URL {
        try ensureDocumentsDirectory()
        let destination = uniqueDestinationURL(for: filename, in: documentsDirectory)
        try FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try data.write(to: destination, options: .atomic)
        return destination
    }

    /// Returns a destination in `directory` that does not collide with an
    /// existing file, appending " (n)" before the extension when needed:
    /// `Report.pdf` -> `Report (1).pdf` -> `Report (2).pdf`.
    func uniqueDestinationURL(for filename: String, in directory: URL) -> URL {
        let candidate = directory.appendingPathComponent(filename)
        guard FileManager.default.fileExists(atPath: candidate.path) else { return candidate }

        let ns = filename as NSString
        let base = ns.deletingPathExtension
        let ext = ns.pathExtension
        var counter = 1
        while true {
            let name = ext.isEmpty ? "\(base) (\(counter))" : "\(base) (\(counter)).\(ext)"
            let next = directory.appendingPathComponent(name)
            if !FileManager.default.fileExists(atPath: next.path) { return next }
            counter += 1
        }
    }

    /// Path of `url` relative to the container Documents directory.
    func relativePath(for url: URL) -> String {
        let base = documentsDirectory.standardizedFileURL.path
        let path = url.standardizedFileURL.path
        let prefix = base.hasSuffix("/") ? base : base + "/"
        guard path.hasPrefix(prefix) else { return url.lastPathComponent }
        return String(path.dropFirst(prefix.count))
    }

    func absoluteURL(forRelativePath path: String) -> URL {
        documentsDirectory.appendingPathComponent(path)
    }

    /// Deletes the file at `path` relative to the Documents directory.
    /// Removing an already-missing file succeeds, so retried deletions
    /// converge; any other failure is surfaced, never swallowed.
    func deleteFile(atRelativePath path: String) throws {
        let url = absoluteURL(forRelativePath: path)
        guard FileManager.default.fileExists(atPath: url.path) else { return }
        do {
            try FileManager.default.removeItem(at: url)
        } catch {
            throw FileBridgeError.deletionFailed(relativePath: path, underlying: error)
        }
    }

    static func fileSize(at url: URL) -> Int64 {
        guard
            let values = try? url.resourceValues(forKeys: [.fileSizeKey]),
            let size = values.fileSize
        else { return 0 }
        return Int64(size)
    }

    /// The file's actual creation date (APFS birth time), independent of when
    /// the app imported or adopted it. nil when the file can't be stat'd.
    static func creationDate(at url: URL) -> Date? {
        (try? url.resourceValues(forKeys: [.creationDateKey]))?.creationDate
    }
}
